### ISSUE TITLE
If applied to a selector, what's the behaviour?

### ISSUE THREAD

**Issue by jakearchibald** [KenjiBaheux/css-font-rendering#10]
``` css
.whatever {
  font-rendering: mandatory 60s;
}

.whatever .foo {
  font-family: foo;
}

.whatever .bar {
  font-family: bar;
}

.whatever .blah {
  font-family: sans-serif;
}
```

Assuming:
- `foo` & `bar` are defined in `@font-face` rules
- `foo` takes 5 seconds to load
- `bar` takes 10 seconds to load
- (I'm also assuming the `font-rendering` in `.whatever` has precedence over rules in `@font-face`)

When does the text in `.foo` render? As in, does it also wait for `bar` as `font-rendering` is set on a parent that uses both fonts? What about the text in `.blah`?
