### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by jakearchibald** [KenjiBaheux/css-font-rendering#11]
We filmed a little show this morning where I spoke about this proposal. I had a hard time working out how I was going to explain what the number part of the proposal, I think that's because it's a separate thing.

How about separating it out?

``` css
@font-face {
  /* ... */
  font-rendering-wait-timeout: [duration];
  font-rendering-swap-timeout: [duration];
  /* or for short… */
  font-rendering: [wait duration]/[swap-duration];
  /* or for shorter… */
  font-rendering: [keyword];

  /* The current Firefox/Chrome/Opera behaviour: */
  font-rendering: 3s/infinite;
  font-rendering: timeout;

  /* The current IE behaviour: */
  font-rendering: 0s/infinite;
  font-rendering: immediate;

  /* The current Safari behaviour: */
  font-rendering: infinite;
  font-rendering: wait;

  /* The Guardian/Smashing Mag approach */
  font-rendering: 0s/0s;
  font-rendering: race;
}
```

@tabatkins is 'infinite' and num/num appropriate here?
